Squashed commit of the following:
commit dc34c0041c41654998111fd3e0ab2abcc426aec1
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Fri Dec 27 22:10:13 2024 +0900

    fix shadows name 'k' from outer scope

    while syntactically correct this triggers a false Unresolved reference 'k' error in PyCharms

commit fc5483350590510368a2886168c4848e8880bfc6
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Fri Dec 27 08:58:44 2024 +0900

    Authenticated Sysinfo

commit 078d04ef23ce2e942e20a93fd60591ad1c177258
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Fri Dec 27 10:40:15 2024 +0900

    ruff <path> is deprecated. Use ruff check <path> (#16753)

commit 1a773bf2c844cc379fb5c80bab7c9894477d193e
Merge: f25c3fc9 f113474a
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Dec 26 06:33:04 2024 +0900

    Merge pull request #16751 from Neokmi/master

    Fix  Codeformer and gfpgan extension , Inconsistent overlay layer types when visibility value is less than 1

commit f113474a6e2fb8857cb344115840b0bc30166f89
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Dec 26 06:26:47 2024 +0900

    lint

commit 6577e063d181b026a33628b085d0a097bba981df
Author: klx <128426349+Neokmi@users.noreply.github.com>
Date:   Thu Dec 26 02:16:05 2024 +0800

    Update postprocessing_gfpgan.py

    Fix  gfpgan extension , Inconsistent overlay layer types when visibility value is less than 1

commit 7953c570d9eb7e5da3fcffbfbf244a32b849cf46
Author: klx <128426349+Neokmi@users.noreply.github.com>
Date:   Thu Dec 26 02:14:49 2024 +0800

    Update postprocessing_codeformer.py

    Fix  Codeformer extension , Inconsistent overlay layer types when visibility value is less than 1

commit f25c3fc9cb57f3f66438027107a6e967d126ee8c
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Wed Dec 25 05:43:55 2024 +0900

    fix sd_vae_explanation (#16748)

commit fc0952abb9592b69f2311e4ede1b82492d312a64
Merge: 04903af7 b414c62c
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Dec 24 22:58:43 2024 +0900

    Merge pull request #16745 from Sanchows/removed-unused-import-modules-errors

    removed unnecessary import 'modules.errors'

commit b414c62ce472ffed895f4d178cdb022f89110394
Author: Alexander Sachenko <35726682+Sanchows@users.noreply.github.com>
Date:   Tue Dec 24 15:45:10 2024 +0300

    removed unnecessary import modules.errors

commit 04903af798f66877f8af00b778e1696c88e517db
Merge: e8c3b1f2 95686227
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Wed Dec 18 03:21:48 2024 +0900

    Merge pull request #16604 from Haoming02/ext-updt-parallel

    Check for Extension Updates in Parallel

commit e8c3b1f2a03aa7418631ff839ea913a499e88adb
Merge: 0120768f 8bf30e3c
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Wed Dec 18 02:37:30 2024 +0900

    Merge pull request #16718 from Haoming02/bracket-checker-order

    [Bracket Checker] Also check for the order of brackets

commit 8bf30e3c42b39a43166e7022865c2c62af9eff96
Author: Haoming <hmstudy02@gmail.com>
Date:   Wed Dec 18 01:02:40 2024 +0800

    revert IIFE

commit fbc51fa210bf689f300135e84a89c4ca9fcb4b5c
Author: Haoming <hmstudy02@gmail.com>
Date:   Mon Dec 16 09:47:38 2024 +0800

    skip escaped

commit 7025a2c4a5c27329ecb0ea526b94c6baa93f5840
Author: Haoming <hmstudy02@gmail.com>
Date:   Thu Dec 12 16:08:15 2024 +0800

    check-for-order

commit 0120768f63dda88192576ee88c63d7f73eefb49a
Merge: 023454b4 b425b97a
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Nov 28 17:39:12 2024 +0900

    Merge pull request #16687 from Haoming02/dropdown4format

    Use gr.Dropdown for Image Formats

commit b425b97ad6a988bebfc55d9e19411383e16ce570
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Nov 28 16:56:10 2024 +0900

    improve img fromat description

commit 539ea3982debad1e416ab2b6a32d91094119a244
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Nov 28 14:02:33 2024 +0900

    use DropdownEditable

    use DropdownEditable so user can input other formats if they require it
    make the default png the first on the list

commit 65bd61e87c5562c4e88dce4d486da06e796cf8df
Author: Haoming <hmstudy02@gmail.com>
Date:   Wed Nov 27 10:42:50 2024 +0800

    format-dropdown

commit 023454b49e6bf2a98804b91a12f84af2f653d128
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Nov 21 11:33:59 2024 +0900

    fix passing of literal backslash (#16671)

commit cd869bb7a35e6a3eb09b8fb48873e583f9e2eaf6
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Nov 21 02:29:41 2024 +0900

    fix prompt-bracket-checker miscounting of literal tokens (#16669)

commit 957888a100cc9fa00ce84d6b38dc3970ce5a2aae
Merge: 7799859f d2c9efb1
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Nov 19 14:41:37 2024 +0900

    Merge pull request #16667 from AUTOMATIC1111/fix/safetensors-bump

    Bump safetensors to v0.4.5

commit d2c9efb1f3ebd53893c9ce98c5a0f36d9d6ac5a9
Author: catboxanon <122327233+catboxanon@users.noreply.github.com>
Date:   Mon Nov 18 20:48:36 2024 -0500

    Bump safetensors to v0.4.5

    Resolves #16650

commit 7799859f9fb8a0428d33e50a867e2407be4b8620
Merge: 1b16c626 ca3bedbd
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sat Nov 2 01:28:12 2024 +0900

    Merge pull request #16620 from AUTOMATIC1111/fix/api-webp-lossless

    Honor lossless WebP compression option in API

commit ca3bedbd02d9b9837641b0e58345f63eac52a8cc
Author: catboxanon <122327233+catboxanon@users.noreply.github.com>
Date:   Fri Nov 1 11:32:52 2024 -0400

    Honor lossless webp compression option in API

commit 1b16c6260819a438d2f7d65110813d227aff9058
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Oct 31 02:01:32 2024 +0900

    use shared.hf_endpoint (#16611)

commit 91de9194512dbf654999bd58be827434ed5cba90
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Wed Oct 30 22:34:37 2024 +0900

    Warn if WebUI is installed under a dot directory (#16584)

commit aa52408aab484bab859132fde7a4b4d9fd851433
Merge: 28323cf8 e6f36d9c
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Wed Oct 30 09:51:41 2024 +0900

    Merge pull request #16606 from AUTOMATIC1111/fix/vweighting

    Fix config for SDXL v-pred

commit e6f36d9cdc42d8008be482d449e85e737f3b989d
Author: catboxanon <122327233+catboxanon@users.noreply.github.com>
Date:   Tue Oct 29 13:27:32 2024 -0400

    sd_xl_v.yaml: use_checkpoint = False

    In accordance with https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/15803

commit 28323cf8ee90594d4a31bb58af2da160dfc85086
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Wed Oct 30 02:18:38 2024 +0900

    XYZ option to disable grid (#16416)

commit 533c7b7b7fb13889a25da570bf1369a998a9371b
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Wed Oct 30 02:13:16 2024 +0900

    Fix Default system None filter logic (#16309)

commit ac28cad998a5c6f09d1cd928f68d9f255ed72622
Author: catboxanon <122327233+catboxanon@users.noreply.github.com>
Date:   Tue Oct 29 11:49:09 2024 -0400

    Fix weighting config for SDXL v-pred

    Fixes a small oversight I made.

commit 5206b938efe617e7747472e12360db9096fa6eb0
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Wed Oct 30 00:03:21 2024 +0900

    InputAccordion duplicate elem_id handling (#16381)

commit 59481435f40b48b89d3565be9804255cf134d522
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Oct 29 23:59:04 2024 +0900

    addEventListener {passive: false} (#16575)

commit f31faf6f14a648fc698b112293c8c9506db17ea2
Author: viking1304 <viking1304@gmail.com>
Date:   Tue Oct 29 15:54:58 2024 +0100

    pyenv-win compatibility - another approach (#16287)

commit 14c6d6cb3ac774eef1ac969bc5b712e878822871
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Oct 29 23:45:45 2024 +0900

    Disable Hires checkpoint if same as First pass checkpoint (#16269)

commit 4ec10bcdc1aa56a46f648205dc857fee5c05c2c1
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Oct 29 23:38:55 2024 +0900

    Fix postprocessing_enable_in_main_ui ScriptPostprocessing elem_id (#16373)

commit 0bf36cf2adbf216cbac74c5f9461f7cacf0c6cb2
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Oct 29 23:35:46 2024 +0900

    extra_only / main_ui_only ScriptPostprocessing (#16374)

commit 820fe8d2b556aaded190f21780afcd1fe5318e39
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Oct 29 23:30:08 2024 +0900

    Allow newline in Extra Network activation text (#16428)

commit deb3803a3ad54d134f66d124c6ce9483ccd9a03a
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Oct 29 23:28:21 2024 +0900

    image embedding data cache (#16556)

commit 95686227bd2f3710ad62299c69966730a27debfa
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Tue Oct 29 20:16:15 2024 +0900

    limit number of simultaneous updates

    shared.opts.concurrent_git_fetch_limit

commit df74c3c6385ddec225aaa630c77c95b9da0363b2
Author: Haoming <hmstudy02@gmail.com>
Date:   Tue Oct 29 14:12:42 2024 +0800

    threading

commit d88a3c15f7139b3ebb683505974d74e99e1b4809
Merge: 38c80432 ee0ad5cc
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 27 10:28:23 2024 +0900

    Merge pull request #16588 from bluelovers/patch-3

    chore(js): avoid lots of `Wake Lock is not supported.`

commit 38c8043229a5c549279f52ea5b74680f772bfa02
Merge: 984b952e d8ad3646
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 27 01:09:41 2024 +0900

    Merge pull request #16523 from changeworld/fix/typo

    Fix typo: Github -> GitHub

commit ee0ad5cceb72f57954f5dcb4774b92e7d1ad7f8e
Author: bluelovers <codelovers@users.sourceforge.net>
Date:   Fri Oct 25 09:59:45 2024 +0800

    chore(js): avoid lots of `Wake Lock is not supported.`

commit 984b952eb30798ea478cb97b7ca79ff32196f4ce
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Thu Oct 24 22:05:51 2024 +0900

    Fix DAT models download (#16302)

commit 5865da28d1800eea27b3a14979e788b17e010afe
Merge: bb1f3919 c2ce1d3b
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 20 11:40:02 2024 +0900

    Merge pull request #16569 from AUTOMATIC1111/feat/ztsnr-auto

    Automatically enable ztSNR based on existence of key in `state_dict`

commit bb1f39196e6f47d200ddbe1a6b4be27157720546
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 20 09:58:53 2024 +0900

    clarify readme: weget ... chmod +x webui.sh (#16251)

commit 6a5976631334745287c1e5a65b9358c88bee164b
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 20 09:56:12 2024 +0900

    Add Skip Early CFG to XYZ (#16282)

    Co-authored-by: Yevhenii Hurin <evgeny.gurin@gmail.com>

commit 65423d2b33a2ea696e6d62186e12a93af272403d
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 20 09:52:47 2024 +0900

    MIME type text/css (#16406)

commit c2bc187ce7e36bd83833058020cdfacc64de3436
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 20 09:51:59 2024 +0900

    fix modalImageViewer preview/result flicker (#16426)

commit d0b27dc906472d87a789b8120a14996a6e57f23e
Merge: bb4cbaf0 cbaaf0af
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 20 09:42:21 2024 +0900

    Merge pull request #16300 from hello2564/fix_NGMS_pr_typo

    fix NGMS pr typo

commit c2ce1d3b9c9be2bef7efd1fe5b5a53424105a1c5
Author: catboxanon <122327233+catboxanon@users.noreply.github.com>
Date:   Sat Oct 19 19:58:13 2024 -0400

    Automatically enable ztSNR based on existence of key in state_dict

commit bb4cbaf0cfababb67eec705a0b680cc33e0cfddc
Merge: c462e5a5 9677b09b
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sun Oct 20 08:27:12 2024 +0900

    Merge pull request #16341 from gutris1/devv

    add break-word for geninfo in pnginfo

commit c462e5a575abd213e4bc005a58a2c060ebcc4c17
Merge: 8b19b752 c9a06d10
Author: catboxanon <122327233+catboxanon@users.noreply.github.com>
Date:   Sat Oct 19 10:51:16 2024 -0400

    Merge pull request #16460 from AUTOMATIC1111/sd-1.5-url

commit 8b19b75270b788f5be985badcdb94aec6f54e8fe
Merge: 907bfb5e 1ae073c0
Author: AUTOMATIC1111 <16777216c@gmail.com>
Date:   Sat Oct 19 17:40:56 2024 +0300

    Merge pull request #16567 from AUTOMATIC1111/feat/sdxl-vpred

    Support and automatically detect SDXL V-prediction models

commit 907bfb5ef0f4b0bd3ff18313872c687c249b057e
Author: AUTOMATIC1111 <16777216c@gmail.com>
Date:   Sat Oct 19 17:33:58 2024 +0300

    add w-e-w and catboxanon to codeowners file

commit 1ae073c052c2a1eb2b3e87464a576451b3197326
Author: catboxanon <122327233+catboxanon@users.noreply.github.com>
Date:   Sat Oct 19 06:53:19 2024 -0400

    Support SDXL v-pred models

commit c9a06d1093df828c7ff1dd356f38cf5ae41c1227
Author: missionfloyd <missionfloyd@users.noreply.github.com>
Date:   Tue Oct 8 16:50:39 2024 -0600

    Use stable-diffusion-v1-5 repo instead

commit d8ad3646170df18d850b658279ee0a14273ebee2
Author: Takashi Takebayashi <changesworlds@gmail.com>
Date:   Thu Oct 3 14:33:37 2024 +0900

    Fix typo

    Github -> GitHub

commit f57ec2b53b2fd89672f5611dee3c5cb33738c30a
Author: missionfloyd <missionfloyd@users.noreply.github.com>
Date:   Tue Sep 3 19:58:29 2024 -0600

    Update stable diffusion 1.5 URL

commit 9677b09b7c9b06f51cfa6a997a32eac69bb63663
Author: gutris1 <132797949+gutris1@users.noreply.github.com>
Date:   Wed Aug 7 17:37:23 2024 +0700

    add break-word for geninfo in pnginfo

commit cbaaf0af0e0e3173edafaca83448ca90c5ac14e1
Author: hello2564 <ksncdos@163.com>
Date:   Wed Jul 31 14:55:30 2024 +0800

    fix NGMS pr typo

commit 48239090f18d07acd8070a7af9da38b0021fdea3
Merge: 850e1492 82a973c0
Author: AUTOMATIC1111 <16777216c@gmail.com>
Date:   Sat Jul 27 15:50:26 2024 +0300

    Merge branch 'master' into dev

commit 850e14923eaa38553cbf7ff4c8d39696b1f9e7ab
Merge: 834297b1 8e0881d9
Author: AUTOMATIC1111 <16777216c@gmail.com>
Date:   Sat Jul 27 15:47:49 2024 +0300

    Merge pull request #16275 from AUTOMATIC1111/fix-image-upscale-on-cpu

    fix image upscale on cpu

commit 8e0881d9abfa4e139f2dbf3c9a072dd8d4b6d1ba
Author: w-e-w <40751091+w-e-w@users.noreply.github.com>
Date:   Sat Jul 27 21:10:20 2024 +0900

    fix image upscale on cpu

    for some reason upscale using cpu will fail with
    RuntimeError: Inplace update to inference tensor outside InferenceMode
    switch from no_grad to inference_mode seems to have fixed it

commit 834297b13d7cd445c7a1745f801ab36b60586648
Merge: 9f5a98d5 c19d0443
Author: AUTOMATIC1111 <16777216c@gmail.com>
Date:   Sat Jul 27 07:09:08 2024 +0300

    Merge branch 'master' into dev